#!/usr/bin/env ruby
# Run Kitchenplan.

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

require 'pathname'

if ENV['USER'] == 'root'
  abort "Run this as a normal user, I'll sudo if I need to."
end

# Put us where we belong, in the root dir of our kitchenplan repo.

Dir.chdir Pathname.new(__FILE__).realpath + ".."

# Flags
require 'optparse'

options = {}
OptionParser.new do |opts|
    opts.banner = 'Usage: kitchenplan [options]'

    opts.on("-d", "--debug", "Show debug information") do |debug|
        options[:debug] = debug
    end

    opts.on("-c", "--update-cookbooks", "Update the Chef cookbooks") do |update_cookbooks|
        options[:update_cookbooks] = update_cookbooks
    end

    options[:chef] = true
    opts.on("--[no-]chef", "Run chef (defaults to yes)") do |chef|
        options[:chef] = chef
    end

    options[:update] = true
    opts.on("--[no-]update", "Run the kitchenplan update (defaults to yes)") do |update|
        options[:update] = update
    end

    opts.separator ""
    opts.separator "Common options:"

    opts.on_tail("-h", "--help", "Show this message") do
        puts opts
        exit
    end

    opts.on_tail("--version", "Show version") do
        puts "1.0.1"
        exit
    end

end.parse!

# Bootstrapping dependencies

if File.exist? '/etc/redhat-release'
    unless system("(gem spec -q bundler > /dev/null 2>&1) || sudo yum install -y rubygem-bundler")
        abort "Failed to install bundler"
    end
    unless system("(rpm -qi ruby-devel > /dev/null 2>&1) || sudo yum install -y ruby-devel")
        abort "Failed to install ruby-devel"
    end
else
    unless system("(gem spec bundler -v > /dev/null 2>&1) || sudo gem install bundler --no-rdoc --no-ri")
        abort "Failed to install bundler"
    end
end

bundle_command = ["sudo", "bundle"]
bundle_command = bundle_command + [ "install", "--binstubs=bin"]
bundle_command << "--verbose" if options[:debug]
bundle_command << "--quiet" unless options[:debug]
warn bundle_command.join(" ") if options[:debug]
unless system *bundle_command
    abort "There was a problem bootstrapping. Run using --debug for more information"
end

# Add local deps to the load path.

require "rubygems"
require "bundler/setup"
require 'json'

# Generate the chef config
$: << File.join((File.expand_path("../", Pathname.new(__FILE__).realpath)), "/lib")
require "kitchenplan/config"
config = Kitchenplan::Config.new

File.open("kitchenplan-attributes.json", 'w') do |out|
    out.write(JSON.pretty_generate(config.config['attributes']))
end

File.open("solo.rb", 'w') do |out|
    out.write("cookbook_path #{Dir.pwd}/cookbooks")
end

# Possibly updating the cookbooks

if config.platform == "debian"
    git_install_command = ["sudo" ,"apt-get", "install", "-y", "git" ]
    warn git_install_command.join(" ") if options[:debug]
    unless system *git_install_command
        abort "Can't install git. Run using --debug if you need more information."
    end
end

unless File.exists?("cookbooks")
    librarian_command = ["bin/librarian-chef", "install", "--clean" ]
    librarian_command << "--verbose" if options[:debug]
    librarian_command << "--quiet" unless options[:debug]
    warn librarian_command.join(" ") if options[:debug]
    unless system *librarian_command
        abort "Can't install Chef cookbooks with librarian-chef. Run using --debug if you need more information."
    end
end

if options[:update_cookbooks]
    librarian_command = ["bin/librarian-chef", "update", "--verbose" ]
    warn librarian_command.join(" ") if options[:debug]
    unless system *librarian_command
        abort "Can't update Chef cookbooks with librarian-chef. Run using --debug if you need more information."
    end
end

# Run Chef
exit 0 unless options[:chef]

chef_command = ["bin/chef-solo"]
chef_command << "--log_level debug" if options[:debug]
chef_command << "-j kitchenplan-attributes.json"
chef_command << "-o #{config.config['recipes'].join(",")}"
warn chef_command.join(" ") if options[:debug]
unless system("sudo -E bash -c '#{chef_command.join(" ")}'")
    abort "There was a problem running chef. Run using --debug for more information"
end
